template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: mvn_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      gitProvider: {{ .Values.gitProvider }}

  - name: mvn_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artifactory }}
      
  - name: cron_trigger_mvn
    type: CronTrigger
    configuration:
      interval: '0 3 * * *'       

pipelines:
  - name: Maven_Quickstart
    steps:
      - name: mvn_build_step
        type: Bash
        configuration:
          inputResources:
            - name: mvn_repo
            - name: cron_trigger_mvn
          integrations:
            - name: {{ .Values.artifactory }}
        execution:
          onStart:
          - which jfrog
          - task: jfrog/setup-jfrog-cli@v0.1.0
            repository: pipelines-tasks-virtual
            input:
              version: "2.35.0"
          onExecute:
          - task: jfrog/maven-build@v0.0.1
            id: maven-build-task
            input:
              deployerSnapshotRepo: {{ .Values.deployerRepo }}
              deployerReleaseRepo: {{ .Values.deployerRepo }}
              resourceName: mvn_repo
              sourceLocation: ""

      - name: publish_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: mvn_build_step
          outputResources:
            - name: mvn_build_info
