template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: mvn_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      gitProvider: {{ .Values.gitProvider }}

  - name: mvn_build_task_gitrepo
    type: GitRepo
    configuration:
      path: bhanurp/mvn_build_task
      gitProvider: {{ .Values.gitProvider }}
      branches:
        include: ^{{ .Values.mainBranch }}$
      cloneProtocol: https

  - name: mvn_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artifactory }}
      
  - name: cron_trigger_mvn
    type: CronTrigger
    configuration:
      interval: '0 3 * * *'       

pipelines:
  - name: Maven_Quickstart
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: docker.jfrog.io/jfrog/pipelines-u20java
            tag: 17
            registry: docker_registry
            autoPull: tru
      jfrogCliVersion: 2
      environmentVariables:
        readOnly:
          JFROG_TASK_DEBUG: "true"
          JFROG_CLI_LOG_LEVEL: DEBUG
    steps:
      - name: mvn_build_step
        type: Bash
        configuration:
          inputResources:
            - name: mvn_repo
            - name: cron_trigger_mvn
            - name: mvn_build_task_gitrepo
          integrations:
            - name: {{ .Values.artifactory }}
        execution:
          onStart:
          - which jfrog
          - jfrog c show
          onExecute:
          - task: $res_mvn_build_task_gitrepo_resourcePath
            id: maven-build-task
            input:
              deployerSnapshotRepo: {{ .Values.deployerRepo }}
              deployerReleaseRepo: {{ .Values.deployerRepo }}
              resourceName: mvn_repo
              sourceLocation: ""

      - name: publish_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: mvn_build_step
          outputResources:
            - name: mvn_build_info
